### ISSUE TITLE
train跑不了

### ISSUE THREAD

**Issue by andrean123** [hanna-xu/EMFusion#3]
想请教老师，train是不是被改了，里面好多bug啊，谢谢老师
runfile('C:/Users/apple/Downloads/EMFusion-main/SPECT-MRI/main.py', wdir='C:/Users/apple/Downloads/EMFusion-main/SPECT-MRI')
Reloaded modules: fnet, spat_ED, spec_ED, M2Cnet, C2Mnet
Traceback (most recent call last):

  File "C:\Users\apple\Downloads\EMFusion-main\SPECT-MRI\main.py", line 40, in <module>
    print("SPEC_INDEX:", SPEC_INDEX)

NameError: name 'SPEC_INDEX' is not defined

**Comment by chen-yuu** [comment]
> 想请教老师，train是不是被改了，里面好多bug啊，谢谢老师 runfile('C:/Users/apple/Downloads/EMFusion-main/SPECT-MRI/main.py', wdir='C:/Users/apple/Downloads/EMFusion-main/SPECT-MRI') Reloaded modules: fnet, spat_ED, spec_ED, M2Cnet, C2Mnet Traceback (most recent call last):
> 
> File "C:\Users\apple\Downloads\EMFusion-main\SPECT-MRI\main.py", line 40, in print("SPEC_INDEX:", SPEC_INDEX)
> 
> NameError: name 'SPEC_INDEX' is not defined

请问train现在能跑了吗
